//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5.CalculatorWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inputs", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Inputs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double firstnumberField;
        
        private double secondnumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double firstnumber {
            get {
                return this.firstnumberField;
            }
            set {
                if ((this.firstnumberField.Equals(value) != true)) {
                    this.firstnumberField = value;
                    this.RaisePropertyChanged("firstnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double secondnumber {
            get {
                return this.secondnumberField;
            }
            set {
                if ((this.secondnumberField.Equals(value) != true)) {
                    this.secondnumberField = value;
                    this.RaisePropertyChanged("secondnumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComputationResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ComputationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calculations", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Calculations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecentCalculationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecentCalculations {
            get {
                return this.RecentCalculationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecentCalculationsField, value) != true)) {
                    this.RecentCalculationsField = value;
                    this.RaisePropertyChanged("RecentCalculations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compute", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Compute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double InputAField;
        
        private double InputBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        private double ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double InputA {
            get {
                return this.InputAField;
            }
            set {
                if ((this.InputAField.Equals(value) != true)) {
                    this.InputAField = value;
                    this.RaisePropertyChanged("InputA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double InputB {
            get {
                return this.InputBField;
            }
            set {
                if ((this.InputBField.Equals(value) != true)) {
                    this.InputBField = value;
                    this.RaisePropertyChanged("InputB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorWebService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name inputs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Lab5.CalculatorWebService.AddResponse Add(Lab5.CalculatorWebService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.AddResponse> AddAsync(Lab5.CalculatorWebService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name inputs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        Lab5.CalculatorWebService.DivideResponse Divide(Lab5.CalculatorWebService.DivideRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Divide", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.DivideResponse> DivideAsync(Lab5.CalculatorWebService.DivideRequest request);
        
        // CODEGEN: Generating message contract since element name inputs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        Lab5.CalculatorWebService.MultiplyResponse Multiply(Lab5.CalculatorWebService.MultiplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.MultiplyResponse> MultiplyAsync(Lab5.CalculatorWebService.MultiplyRequest request);
        
        // CODEGEN: Generating message contract since element name inputs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        Lab5.CalculatorWebService.SubtractResponse Subtract(Lab5.CalculatorWebService.SubtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.SubtractResponse> SubtractAsync(Lab5.CalculatorWebService.SubtractRequest request);
        
        // CODEGEN: Generating message contract since element name getListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getList", ReplyAction="*")]
        Lab5.CalculatorWebService.getListResponse getList(Lab5.CalculatorWebService.getListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getList", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.getListResponse> getListAsync(Lab5.CalculatorWebService.getListRequest request);
        
        // CODEGEN: Generating message contract since element name computationData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertData", ReplyAction="*")]
        Lab5.CalculatorWebService.insertDataResponse insertData(Lab5.CalculatorWebService.insertDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertData", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.insertDataResponse> insertDataAsync(Lab5.CalculatorWebService.insertDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Lab5.CalculatorWebService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Inputs inputs;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Lab5.CalculatorWebService.Inputs inputs) {
            this.inputs = inputs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Lab5.CalculatorWebService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.ComputationResult AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(Lab5.CalculatorWebService.ComputationResult AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Divide", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.DivideRequestBody Body;
        
        public DivideRequest() {
        }
        
        public DivideRequest(Lab5.CalculatorWebService.DivideRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivideRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Inputs inputs;
        
        public DivideRequestBody() {
        }
        
        public DivideRequestBody(Lab5.CalculatorWebService.Inputs inputs) {
            this.inputs = inputs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivideResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.DivideResponseBody Body;
        
        public DivideResponse() {
        }
        
        public DivideResponse(Lab5.CalculatorWebService.DivideResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivideResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.ComputationResult DivideResult;
        
        public DivideResponseBody() {
        }
        
        public DivideResponseBody(Lab5.CalculatorWebService.ComputationResult DivideResult) {
            this.DivideResult = DivideResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Multiply", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.MultiplyRequestBody Body;
        
        public MultiplyRequest() {
        }
        
        public MultiplyRequest(Lab5.CalculatorWebService.MultiplyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Inputs inputs;
        
        public MultiplyRequestBody() {
        }
        
        public MultiplyRequestBody(Lab5.CalculatorWebService.Inputs inputs) {
            this.inputs = inputs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.MultiplyResponseBody Body;
        
        public MultiplyResponse() {
        }
        
        public MultiplyResponse(Lab5.CalculatorWebService.MultiplyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.ComputationResult MultiplyResult;
        
        public MultiplyResponseBody() {
        }
        
        public MultiplyResponseBody(Lab5.CalculatorWebService.ComputationResult MultiplyResult) {
            this.MultiplyResult = MultiplyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Subtract", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.SubtractRequestBody Body;
        
        public SubtractRequest() {
        }
        
        public SubtractRequest(Lab5.CalculatorWebService.SubtractRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Inputs inputs;
        
        public SubtractRequestBody() {
        }
        
        public SubtractRequestBody(Lab5.CalculatorWebService.Inputs inputs) {
            this.inputs = inputs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.SubtractResponseBody Body;
        
        public SubtractResponse() {
        }
        
        public SubtractResponse(Lab5.CalculatorWebService.SubtractResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.ComputationResult SubtractResult;
        
        public SubtractResponseBody() {
        }
        
        public SubtractResponseBody(Lab5.CalculatorWebService.ComputationResult SubtractResult) {
            this.SubtractResult = SubtractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getList", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.getListRequestBody Body;
        
        public getListRequest() {
        }
        
        public getListRequest(Lab5.CalculatorWebService.getListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListRequestBody {
        
        public getListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.getListResponseBody Body;
        
        public getListResponse() {
        }
        
        public getListResponse(Lab5.CalculatorWebService.getListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Calculations[] getListResult;
        
        public getListResponseBody() {
        }
        
        public getListResponseBody(Lab5.CalculatorWebService.Calculations[] getListResult) {
            this.getListResult = getListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertData", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.insertDataRequestBody Body;
        
        public insertDataRequest() {
        }
        
        public insertDataRequest(Lab5.CalculatorWebService.insertDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.Compute computationData;
        
        public insertDataRequestBody() {
        }
        
        public insertDataRequestBody(Lab5.CalculatorWebService.Compute computationData) {
            this.computationData = computationData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab5.CalculatorWebService.insertDataResponseBody Body;
        
        public insertDataResponse() {
        }
        
        public insertDataResponse(Lab5.CalculatorWebService.insertDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Lab5.CalculatorWebService.ComputationResult insertDataResult;
        
        public insertDataResponseBody() {
        }
        
        public insertDataResponseBody(Lab5.CalculatorWebService.ComputationResult insertDataResult) {
            this.insertDataResult = insertDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : Lab5.CalculatorWebService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<Lab5.CalculatorWebService.CalculatorWebServiceSoap>, Lab5.CalculatorWebService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.AddResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.Add(Lab5.CalculatorWebService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public Lab5.CalculatorWebService.ComputationResult Add(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.AddRequest inValue = new Lab5.CalculatorWebService.AddRequest();
            inValue.Body = new Lab5.CalculatorWebService.AddRequestBody();
            inValue.Body.inputs = inputs;
            Lab5.CalculatorWebService.AddResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.AddResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.AddAsync(Lab5.CalculatorWebService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.AddResponse> AddAsync(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.AddRequest inValue = new Lab5.CalculatorWebService.AddRequest();
            inValue.Body = new Lab5.CalculatorWebService.AddRequestBody();
            inValue.Body.inputs = inputs;
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.DivideResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.Divide(Lab5.CalculatorWebService.DivideRequest request) {
            return base.Channel.Divide(request);
        }
        
        public Lab5.CalculatorWebService.ComputationResult Divide(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.DivideRequest inValue = new Lab5.CalculatorWebService.DivideRequest();
            inValue.Body = new Lab5.CalculatorWebService.DivideRequestBody();
            inValue.Body.inputs = inputs;
            Lab5.CalculatorWebService.DivideResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).Divide(inValue);
            return retVal.Body.DivideResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.DivideResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.DivideAsync(Lab5.CalculatorWebService.DivideRequest request) {
            return base.Channel.DivideAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.DivideResponse> DivideAsync(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.DivideRequest inValue = new Lab5.CalculatorWebService.DivideRequest();
            inValue.Body = new Lab5.CalculatorWebService.DivideRequestBody();
            inValue.Body.inputs = inputs;
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).DivideAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.MultiplyResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.Multiply(Lab5.CalculatorWebService.MultiplyRequest request) {
            return base.Channel.Multiply(request);
        }
        
        public Lab5.CalculatorWebService.ComputationResult Multiply(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.MultiplyRequest inValue = new Lab5.CalculatorWebService.MultiplyRequest();
            inValue.Body = new Lab5.CalculatorWebService.MultiplyRequestBody();
            inValue.Body.inputs = inputs;
            Lab5.CalculatorWebService.MultiplyResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).Multiply(inValue);
            return retVal.Body.MultiplyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.MultiplyResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.MultiplyAsync(Lab5.CalculatorWebService.MultiplyRequest request) {
            return base.Channel.MultiplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.MultiplyResponse> MultiplyAsync(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.MultiplyRequest inValue = new Lab5.CalculatorWebService.MultiplyRequest();
            inValue.Body = new Lab5.CalculatorWebService.MultiplyRequestBody();
            inValue.Body.inputs = inputs;
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).MultiplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.SubtractResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.Subtract(Lab5.CalculatorWebService.SubtractRequest request) {
            return base.Channel.Subtract(request);
        }
        
        public Lab5.CalculatorWebService.ComputationResult Subtract(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.SubtractRequest inValue = new Lab5.CalculatorWebService.SubtractRequest();
            inValue.Body = new Lab5.CalculatorWebService.SubtractRequestBody();
            inValue.Body.inputs = inputs;
            Lab5.CalculatorWebService.SubtractResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).Subtract(inValue);
            return retVal.Body.SubtractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.SubtractResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.SubtractAsync(Lab5.CalculatorWebService.SubtractRequest request) {
            return base.Channel.SubtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.SubtractResponse> SubtractAsync(Lab5.CalculatorWebService.Inputs inputs) {
            Lab5.CalculatorWebService.SubtractRequest inValue = new Lab5.CalculatorWebService.SubtractRequest();
            inValue.Body = new Lab5.CalculatorWebService.SubtractRequestBody();
            inValue.Body.inputs = inputs;
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).SubtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.getListResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.getList(Lab5.CalculatorWebService.getListRequest request) {
            return base.Channel.getList(request);
        }
        
        public Lab5.CalculatorWebService.Calculations[] getList() {
            Lab5.CalculatorWebService.getListRequest inValue = new Lab5.CalculatorWebService.getListRequest();
            inValue.Body = new Lab5.CalculatorWebService.getListRequestBody();
            Lab5.CalculatorWebService.getListResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).getList(inValue);
            return retVal.Body.getListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.getListResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.getListAsync(Lab5.CalculatorWebService.getListRequest request) {
            return base.Channel.getListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.getListResponse> getListAsync() {
            Lab5.CalculatorWebService.getListRequest inValue = new Lab5.CalculatorWebService.getListRequest();
            inValue.Body = new Lab5.CalculatorWebService.getListRequestBody();
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).getListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab5.CalculatorWebService.insertDataResponse Lab5.CalculatorWebService.CalculatorWebServiceSoap.insertData(Lab5.CalculatorWebService.insertDataRequest request) {
            return base.Channel.insertData(request);
        }
        
        public Lab5.CalculatorWebService.ComputationResult insertData(Lab5.CalculatorWebService.Compute computationData) {
            Lab5.CalculatorWebService.insertDataRequest inValue = new Lab5.CalculatorWebService.insertDataRequest();
            inValue.Body = new Lab5.CalculatorWebService.insertDataRequestBody();
            inValue.Body.computationData = computationData;
            Lab5.CalculatorWebService.insertDataResponse retVal = ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).insertData(inValue);
            return retVal.Body.insertDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab5.CalculatorWebService.insertDataResponse> Lab5.CalculatorWebService.CalculatorWebServiceSoap.insertDataAsync(Lab5.CalculatorWebService.insertDataRequest request) {
            return base.Channel.insertDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab5.CalculatorWebService.insertDataResponse> insertDataAsync(Lab5.CalculatorWebService.Compute computationData) {
            Lab5.CalculatorWebService.insertDataRequest inValue = new Lab5.CalculatorWebService.insertDataRequest();
            inValue.Body = new Lab5.CalculatorWebService.insertDataRequestBody();
            inValue.Body.computationData = computationData;
            return ((Lab5.CalculatorWebService.CalculatorWebServiceSoap)(this)).insertDataAsync(inValue);
        }
    }
}
